// BundledClamAVRuntime.swift
// Owns the writable Application Support layout the bundled ClamAV needs at runtime — the signature-database directory plus a minimal freshclam.conf.

import Foundation

/// Resolves and lazily provisions the runtime files the bundled ClamAV
/// needs that can't live inside the read-only `.app`.
///
/// The Homebrew `freshclam` we ship was compiled with a default
/// `--config-file` of `/opt/homebrew/etc/clamav/freshclam.conf` and a
/// default `DatabaseDirectory` of `/opt/homebrew/var/lib/clamav`. Both
/// are absent on a user machine, so freshclam exits with status 6
/// ("config file error") if called without a `--config-file` pointing
/// at a conf we own. This type writes that conf — and the writable
/// signature-database directory it points at — under
/// `~/Library/Application Support/VaderCleaner/clamav/`. Both
/// `DatabaseUpdater` and `ClamAVScanner` consume the resulting URLs.
///
/// The root and `FileManager` are injected so the tests run against a
/// temp directory rather than the user's real Application Support.
struct BundledClamAVRuntime {

    private let root: URL
    private let bundleResources: URL?
    private let fileManager: FileManager

    init(
        root: URL = BundledClamAVRuntime.defaultRoot,
        bundleResources: URL? = Bundle.main.resourceURL,
        fileManager: FileManager = .default
    ) {
        self.root = root
        self.bundleResources = bundleResources
        self.fileManager = fileManager
    }

    /// `~/Library/Application Support/VaderCleaner/clamav/`. Picked
    /// rather than `Caches/` because signature databases are several
    /// hundred MB and the OS may evict `Caches/` under pressure —
    /// re-downloading the full DB after every purge would be costly.
    static let defaultRoot: URL = {
        let appSupport = FileManager.default.urls(
            for: .applicationSupportDirectory,
            in: .userDomainMask
        ).first!
        return appSupport
            .appendingPathComponent("VaderCleaner", isDirectory: true)
            .appendingPathComponent("clamav", isDirectory: true)
    }()

    /// `<root>/db/`, created on demand. Returns the URL freshclam writes
    /// signatures into and clamscan reads them from.
    func databaseDirectory() throws -> URL {
        let url = root.appendingPathComponent("db", isDirectory: true)
        try fileManager.createDirectory(
            at: url,
            withIntermediateDirectories: true
        )
        return url
    }

    /// `<root>/etc/freshclam.conf`, created on demand. The file is
    /// written once and never clobbered, so a user who edits it (e.g.
    /// to add a `HTTPProxyServer` line behind a corporate proxy) keeps
    /// their changes across app launches.
    func freshclamConfigFile() throws -> URL {
        let etc = root.appendingPathComponent("etc", isDirectory: true)
        try fileManager.createDirectory(
            at: etc,
            withIntermediateDirectories: true
        )
        let conf = etc.appendingPathComponent(
            "freshclam.conf",
            isDirectory: false
        )
        guard !fileManager.fileExists(atPath: conf.path) else { return conf }

        let db = try databaseDirectory()
        // Minimum freshclam needs to start. Notably absent: the
        // `Example` token Homebrew's sample conf ships with — freshclam
        // refuses to start while that's present, by design.
        let contents = """
        # Generated by VaderCleaner. Edit to customise update behaviour
        # (e.g. add HTTPProxyServer / HTTPProxyPort behind a corporate
        # proxy). This file is written once and never overwritten.
        DatabaseMirror database.clamav.net
        DatabaseDirectory \(db.path)
        """
        try contents.write(to: conf, atomically: true, encoding: .utf8)
        return conf
    }

    /// `<bundle resources>/clamav/certs/`, or `nil` when the cert
    /// directory wasn't staged into the .app (a dev build that opts out
    /// of bundling). Returned URL is read-only — it lives inside the
    /// signed app bundle, not Application Support.
    ///
    /// freshclam (>=1.5) verifies the digital signature on every CVD it
    /// downloads against `clamav.crt`; without `--cvdcertsdir` it looks
    /// at its compiled-in default, which on a Homebrew build is the
    /// Cellar path and so misses on a user machine.
    func bundledCVDCertsDirectory() -> URL? {
        guard let bundleResources else { return nil }
        let certs = bundleResources
            .appendingPathComponent("clamav/certs", isDirectory: true)
        let crt = certs.appendingPathComponent("clamav.crt", isDirectory: false)
        return fileManager.fileExists(atPath: crt.path) ? certs : nil
    }
}
