// CleanupGroup.swift
// Rolls the fine-grained ScanCategory values up into the four high-level cards the Cleanup dashboard presents (System Junk, Trash Bins, Xcode Junk, Document Versions).

import Foundation

/// One card on the Cleanup results dashboard. Several `ScanCategory` values can
/// roll up into a single card — the dashboard groups caches, logs, language
/// files, mail attachments, and iOS backups under one "System Junk" bucket, the
/// way the reference cleaner does, while Trash, Xcode junk, and Document
/// Versions each stand alone. `allCases` order is the on-screen display order:
/// the hero (System Junk) leads, then Trash Bins, Xcode Junk, Document Versions.
enum CleanupGroup: String, CaseIterable, Identifiable {
    case systemJunk
    case trashBins
    case xcodeJunk
    case documentVersions

    var id: String { rawValue }

    /// The scan categories that contribute files and bytes to this card.
    /// `.largeFile` / `.oldFile` are intentionally unmapped — they belong to the
    /// Large & Old Files section, not Cleanup.
    var categories: [ScanCategory] {
        switch self {
        case .systemJunk:
            return [.systemCache, .userCache, .systemLogs, .userLogs,
                    .languageFiles, .mailAttachments, .iosBackups]
        case .trashBins:
            return [.trash]
        case .xcodeJunk:
            return [.xcodeJunk]
        case .documentVersions:
            return [.documentVersions]
        }
    }

    /// The group a category rolls up into, or `nil` for categories that aren't
    /// part of any Cleanup card.
    static func group(for category: ScanCategory) -> CleanupGroup? {
        allCases.first { $0.categories.contains(category) }
    }

    /// The Cleanup Manager category a card's "Review" should open to. The
    /// single-category cards (Trash Bins, Xcode Junk, Document Versions) deep
    /// link straight to that sub-category. System Junk opens to User Caches —
    /// the largest category in its group — so the right pane lands on items that
    /// are part of the card's (pre-selected) group rather than a sibling
    /// category that belongs to a different card.
    var managerCategory: ScanCategory? {
        switch self {
        case .systemJunk:       return .userCache
        case .trashBins:        return .trash
        case .xcodeJunk:        return .xcodeJunk
        case .documentVersions: return .documentVersions
        }
    }

    /// Whether this card offers a direct "Clean" action alongside "Review".
    /// System Junk and Trash Bins are safe to clean wholesale; Xcode Junk and
    /// Document Versions are review-only so the user inspects before removing.
    var allowsDirectClean: Bool {
        switch self {
        case .systemJunk, .trashBins:
            return true
        case .xcodeJunk, .documentVersions:
            return false
        }
    }

    /// Card title, e.g. "System Junk".
    var title: String {
        switch self {
        case .systemJunk:
            return String(localized: "System Junk", comment: "Cleanup dashboard card title.")
        case .trashBins:
            return String(localized: "Trash Bins", comment: "Cleanup dashboard card title.")
        case .xcodeJunk:
            return String(localized: "Xcode Junk", comment: "Cleanup dashboard card title.")
        case .documentVersions:
            return String(localized: "Document Versions", comment: "Cleanup dashboard card title.")
        }
    }

    /// One-line description shown under the card's size headline.
    var blurb: String {
        switch self {
        case .systemJunk:
            return String(
                localized: "Clean up all of the unneeded files generated by your system and applications.",
                comment: "Cleanup dashboard System Junk card description."
            )
        case .trashBins:
            return String(
                localized: "Stop wasting your drive space. Delete the contents of your trash bins for good.",
                comment: "Cleanup dashboard Trash Bins card description."
            )
        case .xcodeJunk:
            return String(
                localized: "Derived data, archives, and old device support left behind by Xcode.",
                comment: "Cleanup dashboard Xcode Junk card description."
            )
        case .documentVersions:
            return String(
                localized: "Saved revisions of edited documents you no longer need.",
                comment: "Cleanup dashboard Document Versions card description."
            )
        }
    }

    /// Asset-catalog name of the glossy 3D badge shown on the card — the same
    /// "Smart Care" artwork family used elsewhere. Sources and the bake script
    /// live in `Scripts/ScanBadges`.
    var badgeAsset: String {
        switch self {
        case .systemJunk:       return "scanBadgeCleanupSystemJunk"
        case .trashBins:        return "scanBadgeTrash"
        case .xcodeJunk:        return "scanBadgeXcodeJunk"
        case .documentVersions: return "scanBadgeDocumentVersions"
        }
    }
}

/// One Cleanup dashboard card's data: its group, the files rolled up across the
/// group's categories, and the aggregated count and byte total. Built from a
/// `ScanResult` so the dashboard never re-walks files to size a card.
struct CleanupGroupTile: Identifiable, Equatable {
    let group: CleanupGroup
    let files: [ScannedFile]
    let count: Int
    let totalBytes: Int64

    var id: String { group.rawValue }

    init(group: CleanupGroup, files: [ScannedFile], totalBytes: Int64) {
        self.group = group
        self.files = files
        self.count = files.count
        self.totalBytes = totalBytes
    }

    /// One tile per group that has findings, in `CleanupGroup.allCases` (display)
    /// order. Groups with no scanned files are omitted so the dashboard never
    /// shows an empty card. Byte totals are summed from the result's precomputed
    /// `sizeByCategory` so the tile never re-sums files.
    static func tiles(from result: ScanResult) -> [CleanupGroupTile] {
        CleanupGroup.allCases.compactMap { group in
            let files = group.categories.flatMap { result.itemsByCategory[$0] ?? [] }
            guard !files.isEmpty else { return nil }
            let bytes = group.categories.reduce(Int64(0)) { $0 + (result.sizeByCategory[$1] ?? 0) }
            return CleanupGroupTile(group: group, files: files, totalBytes: bytes)
        }
    }
}
